on:
  push:
    branches: [main]

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Pull submodules
        run: git submodule update --init --recursive --depth 1

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install OS dependencies and tools
        run: |
          sudo apt-get update
          sudo apt-get install -y make build-essential \
            libssl-dev zlib1g-dev libbz2-dev libreadline-dev \
            libsqlite3-dev wget curl llvm libncurses5-dev \
            libncursesw5-dev xz-utils tk-dev liblzma-dev tk-dev

      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt

      - run: source ./build_cpython_for_wasm.sh
      - name: Build to ./out
        run: |
          pushd emsdk
          source ./emsdk_env.sh
          popd
          emmake make RELEASE=1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./out"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
